### ISSUE TITLE
Engine configuration in package.json and Yarn

### ISSUE THREAD

**Issue by matteoantoci** [webpro/dyson-generators#1]
I started using Yarn for packages installation. By default Yarn checks for compatibility issues with engines specified in package.json.

In `dyson-generators` I see there's set `"node": "0.8.x"`. Is there a reason to do this? If not, could you please update the engine configuration setting with something like `"node": ">=0.8"`?

Thanks!

**Comment by danday74** [comment]
same problem. unable to install with yarn due to "node": "0.8.x"

had to use `npm install` instead

**Comment by webpro** [comment]
I've removed the `engines` field from `package.json` in v0.2.0.

**Comment by danday74** [comment]
that fixed it thanks :)
