### ISSUE TITLE
Question: returning from localhost?

### ISSUE THREAD

**Issue by thevangelist** [webpro/dyson-generators#2]
How can I return images relative to the mock .js file?

**Comment by webpro** [comment]
Hi @thevangelist. This lib returns base64 strings (not paths to images). So I'm not sure what you are trying to achieve.

Maybe you are also using https://github.com/webpro/dyson-image to serve dummy images from a specific path?

**Comment by thevangelist** [comment]
Thanks, I solved this by using dyson-image!
